pipeline {
    agent {
        label 'node1'
    }

    tools {
        git 'Default'
    }

    stages {
        stage('Echo') {
            steps {
                sh "chmod -R 755 ${env.WORKSPACE}"
            }
        }

        stage('Clone Repository') {
            steps {
                script {
                    //Specify the target directory
                    def targetDir = "${env.WORKSPACE}"
                    //Clone the repo into the specified directory
                    dir(targetDir) {
                        git branch: "main", url: "https://github.com/Pearlicia/flask-app.git"
                    }
                }
            }
        }

        stage('Deploy with Playbook') {
            steps {
                //Execute ansible playbook for deployment
                sh "cd ${env.WORKSPACE}/ && ansible-playbook flask-install.yml -i hosts.ini"
            }
        }
    }

    post {
        success {
            mail to: "feliciaebikon@gmail.com",
            subject: "Flask App Succesful",
            body: "Check console output for details"
        }

        failure { 
            mail to: "feliciaebikon@gmail.com",
            subject: "Flask App Failed",
            body: "Check console output for details"
        }
    }
}